sending test

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -38,6 +38,7 @@ jobs:
         pip install -r requirements.txt
 
     - name: Run tests with pytest and capture results
-      run: pytest -n auto --telegram_id=$TELEGRAM_BOT_TOKEN --telegram_token=$TELEGRAM_CHAT_ID
+      run: pytest -n auto --telegram_id=$TELEGRAM_BOT_TOKEN --telegram_token=$TELEGRAM_CHAT_ID > test_output.txt || echo "Test failed"
+        cat test_output.txt
 
 
